SELECT * FROM TBCLIENTE WHERE UPPER(NOMECLI) LIKE upper('b%');

SELECT SUM(SALARIOCLI), SUM(SALARIOCLI + 10), COUNT(PKCODCLI), AVG(SALARIOCLI), MAX(SALARIOCLI), MIN(SALARIOCLI) FROM TBCLIENTE;

SELECT SEXOCLI, COUNT(SEXOCLI) AS "QUANTIDADE SEXO", SUM(SALARIOCLI) as "QUANTIDADE SALARIO" from TBCLIENTE HAVING COUNT(SEXOCLI) > 3 GROUP BY SEXOCLI;
SELECT * FROM (SELECT SEXOCLI, COUNT(SEXOCLI) AS "QUANTIDADE SEXO", SUM(SALARIOCLI) as "QUANTIDADE SALARIO" from TBCLIENTE GROUP BY SEXOCLI) WHERE "QUANTIDADE SEXO" > 3;

SELECT * FROM TBCLIENTE c WHERE c.PKCODCLI>=2 AND c.SEXOCLI='F';
SELECT * FROM TBCLIENTE c WHERE c.PKCODCLI=2 OR c.PKCODCLI=5;
SELECT * FROM TBCLIENTE c WHERE c.PKCODCLI IN(2, 3, 5, 8);
SELECT * FROM TBCLIENTE c WHERE c.PKCODCLI IN (SELECT MAX(PKCODCLI) FROM TBCLIENTE) OR c.PKCODCLI IN (SELECT MIN(PKCODCLI) FROM TBCLIENTE);
SELECT * FROM TBCLIENTE;

UPDATE TBCLIENTE c SET c.ENDCLI='Av Brasil', c.SALARIOCLI=500 WHERE c.PKCODCLI=2;
UPDATE TBCLIENTE c SET  c.SALARIOCLI=c.SALARIOCLI + (c.SALARIOCLI * 10 / 100);

DELETE FROM TBCLIENTE WHERE PKCODCLI=3

SELECT p.NOMEPROD, c.NOMECAT from TBPRODUTO p, TBCATEGORIA c where p.FKCODCAT=c.PKCODCAT;

select p.NOMEPROD, c.NOMECAT from TBPRODUTO p INNER JOIN TBCATEGORIA c on p.FKCODCAT=c.PKCODCAT;

SELECT * FROM TBPRODUTO p INNER JOIN TBFORNECEDOR f ON f.PKCODFORN=p.FKCODFORN;

SELECT * FROM TBPRODUTO p LEFT JOIN TBFORNECEDOR f ON f.PKCODFORN=p.FKCODFORN;

SELECT * FROM TBPRODUTO p RIGHT JOIN TBFORNECEDOR f ON f.PKCODFORN=p.FKCODFORN;

SELECT * FROM TBPRODUTO p FULL JOIN TBFORNECEDOR f ON f.PKCODFORN=p.FKCODFORN;

SELECT * FROM TBPRODUTO p INNER JOIN TBFORNECEDOR f on f.PKCODFORN=p.FKCODFORN WHERE UPPER(f.NOMEFORN) like UPPER('%x%');

UPDATE TBPRODUTO p SET p.ESTOQUEPROD=p.ESTOQUEPROD + 1 WHERE p.FKCODFORN in (SELECT f.PKCODFORN FROM TBFORNECEDOR f WHERE UPPER(f.NOMEFORN) like UPPER('%x%'));

SELECT c.NOMECAT FROM TBCATEGORIA c UNION SELECT f.NOMEFORN FROM TBFORNECEDOR f;
